server:
  port: 8001
spring:
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 1000


zookeeper:
  addr: 192.168.200.130:2181

metaServer:
  host: 127.0.0.1



